# Generated by Django 2.0.1 on 2019-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joinnning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Course', models.CharField(max_length=25)),
                ('DOJ', models.CharField(max_length=25)),
                ('DOC', models.CharField(max_length=25)),
                ('Course_fee', models.CharField(max_length=25)),
                ('Instructor', models.CharField(max_length=25)),
                ('Aadhar', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('remark', models.CharField(max_length=25)),
            ],
        ),
    ]
