# Generated by Django 2.0.1 on 2019-10-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_joinnning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joinnning',
            new_name='Join',
        ),
    ]
