# Generated by Django 2.0.1 on 2019-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191014_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='status',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
